title: Evilsaint Cloud
email: cloud@evilsaint.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Evilsaint Cloud
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: minima
plugins:
  - jekyll-feed